FROM oven/bun:latest AS build
WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY ./src ./src
ENV NODE_ENV=production
RUN bun build --compile --minify-whitespace --minify-syntax --target bun \
    --outfile server src/index.ts

FROM gcr.io/distroless/base
WORKDIR /app
COPY --from=build /app/server server
ENV NODE_ENV=production
EXPOSE 80
CMD ["./server"]
